Project Setup
Agile-Waterfall-Inc/flooq pull request #18
Opened 2022-03-09 13:34 UTC by MrF3lix

- [x] Frontend using Next.js \w Typescript
- [ ] API using ASP.net Core
- [ ] Executor using Node.js \w Typescript

2022-03-09 20:23 UTC, MrF3lix commented
Once the setup is merged we can start setting up the GitHub workflows.

2022-03-09 22:18 UTC, S4nvers approved these changes
I don't really know react, but to me everything looks good

2022-03-10 07:40 UTC, riesentoaster requested changes

2022-03-10 07:40 UTC, riesentoaster commented on src/executor/package.json
> +    "eslint-config-airbnb-base": "^15.0.0",
Dude.

2022-03-10 07:56 UTC, riesentoaster approved these changes

2022-03-10 08:38 UTC, DuplosFidibuss approved these changes

2022-03-10 09:55 UTC, silvan-flum approved these changes
Tiptop, thanks.

2022-03-10 13:28 UTC, nikipuk approved these changes
Working for me now 🏎️

2022-03-10 13:28 UTC, merged