Refactoring and Clean Code of the DataFlow API
Agile-Waterfall-Inc/flooq pull request #72
Opened 2022-04-07 07:13 UTC by silvan-flum

## Content of this PR

1. Code smells were removed.
2. Documentation in IDataFlowService.cs was added.
3. Flooq database generates the uuid now by itself (when POSTing a **new** data flow). Consequently, the uuid is now nullable when POSTing a **new** data flow.
4. The DataFlowController now adjusts the lastEdited field automatically when a DataFlow is overriden with PUT.

## Related Issues

No related issues.

## Definition of Done

- [x] Code
  - [x] No more code needed
  - [x] No known bugs
- [x] Clean Code
  - [x] Comments have been created for new code
  - [x] No unavoidable Code Smells
- [x] Testing
  - [x] Existing Tests pass
- [x] SonarCloud Quality Gate passed

## Definition of more than Done (optional)

- [ ] Testing
  - [ ] New Integration Tests created
  - [ ] New Integration Tests passed

2022-04-07 09:00 UTC, nikipuk commented
the code sells sound to me like it is not clearly defined, what is nullable or not

2022-04-08 13:34 UTC, DuplosFidibuss requested changes
Very good refactoring. Please have a look at the two comments.

2022-04-08 13:34 UTC, DuplosFidibuss commented on src/api/Flooq.Api/Services/IDataFlowService.cs
> +  /// <param name="entityState">Defines the action of the new DataFlow entry.</param>
Not quite clear what you mean here - is a new data flow created in any case? Otherwise the expression "The new DataFlow" would not be precise.

2022-04-08 13:34 UTC, DuplosFidibuss commented on src/api/Flooq.Api/Services/IDataFlowService.cs
> +  /// </summary>
Which context?

2022-04-11 11:24 UTC, MrF3lix commented
@nikipuk will you do the necessary changes in the editor?

2022-04-13 21:21 UTC, nikipuk reviewed
Do the Migrations have to stay in the project?

2022-04-13 21:22 UTC, nikipuk commented
> @nikipuk will you do the necessary changes in the editor?

I did

2022-04-14 12:36 UTC, DuplosFidibuss approved these changes

2022-04-14 12:39 UTC, merged