UC: Save linearized graph
Agile-Waterfall-Inc/flooq pull request #85
Opened 2022-04-14 17:31 UTC by silvan-flum

## Related Issues

- Closes #78 

## Definition of Done

- [ ] User Story
  - [ ] All Acceptance Criteria met
- [ ] Code
  - [ ] No more code needed
  - [ ] No known bugs
- [ ] Clean Code
  - [ ] Comments have been created for new code
  - [ ] ESLinter found no issues (editor & executor only)
  - [ ] No unavoidable Code Smells
- [ ] Testing
  - [ ] Existing Tests pass
  - [ ] New Unit Tests created
  - [ ] New Unit Tests pass
- [ ] SonarCloud Quality Gate passed

## Definition of more than Done (optional)

- [ ] Testing
  - [ ] New Integration Tests created
  - [ ] New Integration Tests passed

2022-04-23 15:01 UTC, DuplosFidibuss requested changes
Looks good overall. Would be good if another executor expert could have a look at this, too. @S4nvers  could you do that?

2022-04-24 10:15 UTC, silvan-flum commented on src/api/Flooq.IntegrationTest/LinearizedGraphTest.cs
> +    };
No, it's different here. The associated graph has the same id as the data flow. Consequently, the id has to be set in a POST operation.

2022-04-24 10:17 UTC, silvan-flum commented on src/api/Flooq.Test/Controllers/LinearizedGraphControllerTest.cs
> +    var actionResultReceived = await graphController.GetGraph(_graph.Id);
Copy-paste is a skill that has to be learnt...  Changed it.

2022-04-24 10:20 UTC, silvan-flum commented on src/api/Flooq.Test/Controllers/LinearizedGraphControllerTest.cs
> +    Assert.IsNull(graph);
Done.

2022-04-24 10:23 UTC, silvan-flum commented on src/api/Flooq.Test/Services/LinearizedGraphServiceTest.cs
> +  }
Done.

2022-04-24 15:52 UTC, DuplosFidibuss approved these changes

2022-04-25 08:08 UTC, S4nvers requested changes

2022-04-25 08:08 UTC, S4nvers commented on src/executor/source/executor/Linearization.ts
> +export async function linearize( dataflow: Dataflow ): Promise<any> {
- Why is this function async? There is no await or similar in its body.
- Is the any-type in the Promise really necessary or can this be typed even stronger? The function should return a LinearizedDataflow-object only right?

2022-04-25 08:08 UTC, S4nvers commented on src/executor/spec/executor/Linearization.spec.ts
>  } )
Same thing as above. I don't think the linearize-function needs to be async.
Multiple lines in this file are affected, but I don't think every line needs it's own comment

2022-04-25 08:08 UTC, S4nvers commented on src/executor/spec/routes/DataflowRouter.spec.ts
> +  } )
The async linearize-function again

2022-04-26 12:32 UTC, S4nvers approved these changes

2022-04-26 13:34 UTC, merged